# process-compose
version: "0.5"

processes:
  db:
    command: make db
    ready_log_line: "Web Service listening"
  server:
    command: make server
    depends_on:
      db:
        condition: process_log_ready
