name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run tests
        # retry to get around "resource busy"
        # and other transient failures
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: devbox run test
